Adding safe casts header and implementation
TexasInstruments/tiovx pull request #5
Opened 2023-12-22 14:43 UTC by stephenramm

@lcweaver 
Added the khr safe casts extension header (not approved/ratified yet)
Added an implementation very similar to the khronos example implementation in the docs repo
No tests added - this will be a separate PR

2024-02-21 09:03 UTC, stephenramm commented on conformance_tests/test_tiovx/test_safe_casts.c
> +        printf("\nTesting vxCastRefAs and vxGetRefAs for %s\n", type_name);
Not strictly required - was for information only. I will remove.

2024-02-21 09:03 UTC, stephenramm commented on conformance_tests/test_tiovx/test_safe_casts.c
> +    vx_graph graph = vxCreateGraph(context_->vx_context_);
will do

2024-02-21 09:03 UTC, stephenramm commented on conformance_tests/test_tiovx/test_safe_casts.c
> +    vxReleaseGraph(&graph);
will do

2024-02-21 09:03 UTC, stephenramm commented on conformance_tests/test_tiovx/test_safe_casts.c
> +        printf("\nTesting vxCastRefFrom and vxGetRefFrom for %s\n", type_name);
Not strictly required - was for information only. I will remove.

2024-02-21 09:04 UTC, stephenramm commented on source/framework/vx_safe_casts.c
> +            ownIncrementReference(ref, VX_EXTERNAL);
OK

2024-02-21 09:04 UTC, stephenramm commented on source/framework/vx_safe_casts.c
> +            ownIsValidContext(ref->context))
OK

2024-02-21 09:04 UTC, stephenramm commented on source/framework/vx_safe_casts.c
> +         ownIsValidContext(ref->context))
OK

2024-02-21 09:04 UTC, stephenramm commented on source/framework/vx_safe_casts.c
> +        VX_SUCCESS == *status)
OK

2024-02-21 09:04 UTC, stephenramm commented on source/framework/vx_safe_casts.c
> +        VX_SUCCESS == *status)
OK

2024-02-21 15:45 UTC, lcweaver requested changes

2024-02-21 15:45 UTC, lcweaver commented on conformance_tests/test_tiovx/test_safe_casts.c
> +    ASSERT_VX_OBJECT(graph);)
It looks like the ASSERT_VX_OBJECT requires two arguments, the second being the OpenVX type

2024-02-21 15:45 UTC, lcweaver commented on conformance_tests/test_tiovx/test_safe_casts.c
> +    ASSERT_VX_OBJECT(graph);
It looks like the ASSERT_VX_OBJECT requires two arguments, the second being the OpenVX type

2024-02-21 15:45 UTC, lcweaver commented on conformance_tests/test_tiovx/test_safe_casts.c
> +            ASSERT_VX_OBJECT(ref);
It looks like the ASSERT_VX_OBJECT requires two arguments, the second being the OpenVX type

2024-02-21 15:45 UTC, lcweaver commented on conformance_tests/test_tiovx/test_safe_casts.c
> +            ASSERT_VX_OBJECT(ref);
It looks like the ASSERT_VX_OBJECT requires two arguments, the second being the OpenVX type

2024-02-21 15:45 UTC, lcweaver commented on source/framework/vx_safe_casts.c
> +            ownIsValidContext(ref->context))
It looks like this is still pending.  I'll leave it marked as unresolved for now in that case

2024-02-21 15:45 UTC, lcweaver commented on source/framework/vx_safe_casts.c
> +        (VX_SUCCESS == *status))
It looks like this VX_SUCCESS still needs a cast

2024-02-21 15:45 UTC, lcweaver commented on source/framework/vx_safe_casts.c
> +        (VX_SUCCESS == *status))
It looks like this VX_SUCCESS still needs a cast

2024-02-28 21:58 UTC, lcweaver commented
Can you please squash the commits into a single commit with the tag [TIOVX-1540] within the first line of the commit message?

Additionally, please be sure to remove the merge commit when doing so

2024-02-28 21:58 UTC, lcweaver requested changes

2024-03-01 08:36 UTC, closed without merging